apiVersion: v1
kind: ConfigMap
metadata:
  name: games-config
  namespace: games
  labels:
    app: games
data:
  AWSSettings__Region: "us-east-1"
  AWS__AccountId: "${AWS_ACCOUNT_ID}"
  AWSSettings__SQS__GamePurchaseRequested: "game-purchase-requested"
  AWSSettings__SQS__GamePurchaseCompleted: "game-purchase-completed"
  PATH_BASE: "/api/games"
  ASPNETCORE_URLS: "http://+:8080"
  ASPNETCORE_HTTP_PORT: "8080"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
  XRay__ServiceName: "fcg-games-service"
  XRay__TracingDisabled: "false"
