apiVersion: v1
kind: Secret
metadata:
  name: games-secret
  namespace: games
  labels:
    app: games
type: Opaque
stringData:
  MongoDbSettings__ConnectionString: "${MONGO_CONNECTION}"
  MongoDbSettings__DatabaseName: "${MONGO_DATABASE}"
  AWS_ACCESS_KEY_ID: "${KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${KEY_SECRET}"
  AWS_SESSION_TOKEN: "${KEY_TOKEN}"
  ElasticSettings__ApiKey: "${ELASTIC_API_KEY}"
  ElasticSettings__CloudId: "${ELASTIC_CLOUD_ID}"
  OTEL_RESOURCE_ATTRIBUTES: "${OTEL_RESOURCE_ATTRIBUTES}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
  OTEL_EXPORTER_OTLP_HEADERS: "${OTEL_EXPORTER_OTLP_HEADERS}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "${OTEL_EXPORTER_OTLP_PROTOCOL}"
  AWSSettings__ServiceURL: "${AWS_SERVICE_URL}"
  AWSSettings__SQS__GamePurchaseRequested: "${SQS_GAME_PURCHASE_REQUESTED}"
  AWSSettings__SQS__GamePurchaseCompleted: "${SQS_GAME_PURCHASE_COMPLETED}"
